#!/bin/sh

N=5 # number of times a test is repeated (to get an average)

# TIP: You can edit the list of input sizes below
for size in 1000000 2000000 3000000 4000000 5000000 6000000 7000000 8000000 16000000
do
	# TIP: You can edit the list of input types below
	#      For example, you could remove 'random' if you don't want to
	#      time with random input
	# for order in sorted
	# do
	# 	echo === Testing for $order input, size $size ===
	# 	for i in $(seq $N)
	# 	do
	# 		case $order in
	# 			random)   flag="R" ;;
	# 			sorted)   flag="A" ;;
	# 			reversed) flag="D" ;;
	# 		esac
	# 		{ ./gen $size $flag | /usr/bin/time -f "%U" ./sortA > /dev/null ; }
	# 		#                          TIP: replace this ^ with ./sortA or ./sortB
	# 	done
	# 	echo ""
	# done
	echo === Testing for input, size $size ===
	for i in $(seq $N)
	do
		./genQS $size | /usr/bin/time -f "%U" ./sortB > /dev/null ;
	done
	echo ""
done


