/**
 * 1️⃣ FACTORY FUNCTION
 * Creates a standalone Google Form based on a list of Question Keys.
 * Includes support for Checkboxes, Dates, and File Uploads.
 * * @param {string} title - The title of the form
 * @param {string[]} keys - Array of keys matching the QUESTIONS object
 * @returns {object} - Returns { form: Form, id: string }
 */
const createFormWithQuestions = (title, keys) => {
  const form = FormApp.create(title);

  keys.forEach(key => {
    const q = QUESTIONS[key];
    let item;

    switch (q.type) {
      
      // --- CHECKBOXES (Tick boxes) ---
      case 'CHECKBOX':
        item = form.addCheckboxItem();
        item.setTitle(q.text).setRequired(q.required);
        
        if (q.options) {
          const hasOther = q.options.includes("Other");
          const cleanOptions = q.options.filter(opt => opt !== "Other");
          
          item.setChoiceValues(cleanOptions);
          if (hasOther) item.showOtherOption(true);
        }
        break;

      // --- MULTIPLE CHOICE (Radio buttons) ---
      case 'MULTIPLE_CHOICE':
        item = form.addMultipleChoiceItem();
        item.setTitle(q.text).setRequired(q.required);
        
        if (q.options) {
          const hasOther = q.options.includes("Other");
          const cleanOptions = q.options.filter(opt => opt !== "Other");
          
          item.setChoiceValues(cleanOptions);
          if (hasOther) item.showOtherOption(true);
        }
        break;

      // --- DATE INPUTS ---
      case 'DATE':
        item = form.addDateItem();
        item.setTitle(q.text).setRequired(q.required);
        break;

      // --- FILE UPLOADS ---
      case 'FILE_UPLOAD':
        // Note: This forces the form to collect emails and requires login
        item = form.addFileUploadItem();
        item.setTitle(q.text).setRequired(q.required);
        break;

      // --- LONG TEXT (Paragraph) ---
      case 'PARAGRAPH':
        item = form.addParagraphTextItem();
        item.setTitle(q.text).setRequired(q.required);
        break;

      // --- SHORT TEXT (Default) ---
      case 'SHORT_TEXT':
      default:
        item = form.addTextItem();
        item.setTitle(q.text).setRequired(q.required);
        break;
    }
  });

  return {
    form: form,
    id: form.getId()
  };
};
/**
 * Sign Up Sheets
 * Orchestrates the creation of the specific Campus form and links it to the sheet.
 * * @param {string} campus - e.g., 'north', 'south', 'west', 'combined'
 */
const createSignUpForm = (campus) => {
  const ss = SpreadsheetApp.getActive();
  
  // Setup Names
  const campusNameCapitalized = campus.charAt(0).toUpperCase() + campus.slice(1);
  const formName = `Connect ${campusNameCapitalized} Sign Up`;
  const databaseSheetName = SHEETS[campus].DATABASE;

  // Define the specific questions for this form
  const questionKeys = [
    "FIRST_NAME",
    "LAST_NAME",
    "PHONE",
    "EMAIL",
    "SCHOOL",
    "CHURCH",
    "PROMO",
    "FAITH",
    "PHOTO"
  ];

  // --- CALL THE FACTORY FUNCTION ---
  const { form, id } = createFormWithQuestions(formName, questionKeys);

  // Link to Spreadsheet
  form.setDestination(FormApp.DestinationType.SPREADSHEET, ss.getId());

  // Rename the sheet
  // We sleep briefly to ensure the sheet is fully generated by Google's backend
  Utilities.sleep(2000);
  
  const formResponsesSheet = ss.getSheets().find(s => s.getName().startsWith("Form Responses"));
  if (formResponsesSheet) {
    formResponsesSheet.setName(databaseSheetName);
  }

  Logger.log(`Form created: ${form.getEditUrl()}`);
  Logger.log(`Linked to sheet: ${databaseSheetName}`);
};